<a href="https://colab.research.google.com/github/Mgobeaalcoba/Pandas-y-Numpy/blob/main/arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista) # Convierto en array mi lista

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],
         [4,5,6],
         [7,8,9]]

In [ ]:
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#indexado: Empiezan desde cero y no desde uno. 
arr[1]

2

In [ ]:
arr[3] + arr[6]

11

In [ ]:
matriz[0][2] # Se puede hacer con comas entre los corchetes o con dos pares de corchetes

3

In [ ]:
matriz[0,2]

3

In [ ]:
#Slicing
arr[0:3]

array([1, 2, 3])

In [ ]:
arr[2:5]

array([3, 4, 5])

In [ ]:
arr[:5]

array([1, 2, 3, 4, 5])

In [ ]:
arr[4:]

array([5, 6, 7, 8, 9])

In [ ]:
arr[4::2] # De cuatro hasta el final de 2 en 2

array([5, 7, 9])

In [ ]:
matriz[1:,1:] # Slicing de matrices

array([[5, 6],
       [8, 9]])