<a href="https://colab.research.google.com/github/Mgobeaalcoba/Pandas-y-Numpy/blob/main/conditions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.linspace(1,10,10, dtype='int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [4]:
indices_cond = arr > 5 # Verifico con lista booleana de quienes cumplen con la condición

In [5]:
arr[0]

1

In [6]:
arr[1:4]

array([2, 3, 4], dtype=int8)

In [7]:
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [8]:
arr[arr>5] # Es igual al anterior.

array([ 6,  7,  8,  9, 10], dtype=int8)

In [10]:
arr[(arr > 5) & (arr <9)] # Puedo sumar varias condiciones mediante el & y agrupando cada condición entre parentesis

array([6, 7, 8], dtype=int8)

In [11]:
arr[arr>5] = 99 #Modifico solo los que cumplen alguna condición
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [12]:
arr[arr==99] # Me trae solo aquellos donde arr es igual a 99

array([99, 99, 99, 99, 99], dtype=int8)

Todo esto sirve para filtar dataframes o cualquier tipo de estructura de datos. 

Clave para el analisis de datos y el data science