In [ ]:
import numpy as np

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo_de_arr = arr[0:6] # Hago slicing para recortar mi array original / Sigo haciendo referencia al objeto en memoria arr
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo_de_arr[:] = 0 # Modifico mi trozo de array completandolo con ceros
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr #Al revisar mi array original tmb fue modificado por no usar el metodo copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy = arr.copy()
arr_copy

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [ ]:
arr_copy[:] = 100
arr_copy # Al hacer un copy estoy utilizando otro espacio en memoria. Por lo que al modificarlo tengo la seguridad de no estar usando el objeto original. 

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])