<a href="https://colab.research.google.com/github/Mgobeaalcoba/Pandas-y-Numpy/blob/main/creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Uso range de Python para armar listas si quiero
list(range(0,10)) #Es una lista de python

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
#Puedo volverla array así:
arr = np.array(list(range(0,10)))
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
#Pero tmb puedo hacerlo directamente desde Numpy así:
arr = np.arange(0,20,2) # array de 0 19 de 2 en 2
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
# Otro metodo muy usado en ciencia de datos es np.zeros o np.one para crear estructuras vacias
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [13]:
# Puedo crear distribuciones normales de datos planteando el inicio, el fin y cuantos datos quiero en mi vector con linspace
np.linspace(0,100,10)

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [14]:
# Para los amantes del algebra podemos crear una matriz cuadrada de X dimensiones mediante el np.eye(X) donde la diagonal principal va a estar rellena de unos mientras el resto serán ceros
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
# Tmb puedo crear escalares, vectores, matrices y tensores conformados de numeros aletorios mediante np.random.rand
np.random.rand() #Escalar

0.9983328364687793

In [16]:
np.random.rand(5) #Vector de 5 escalares

array([0.81498151, 0.95295787, 0.53873117, 0.30320738, 0.35333306])

In [17]:
np.random.rand(10,10) #Matriz cuadrada de 10x10

array([[0.96537359, 0.82409694, 0.48693909, 0.62563372, 0.3883387 ,
        0.84068688, 0.6654849 , 0.30983136, 0.89091087, 0.29680438],
       [0.7346594 , 0.13506734, 0.83222861, 0.8306256 , 0.22612405,
        0.41315246, 0.31027155, 0.14089035, 0.86395632, 0.71275379],
       [0.64576992, 0.42574446, 0.04571647, 0.19663371, 0.3796517 ,
        0.41779276, 0.02149206, 0.71143585, 0.11388421, 0.25213734],
       [0.30823298, 0.16030408, 0.881826  , 0.67295834, 0.75411089,
        0.40420586, 0.91454464, 0.12690747, 0.15534146, 0.18028582],
       [0.94334598, 0.76758859, 0.69487774, 0.93380889, 0.54289475,
        0.35182704, 0.70555969, 0.10982166, 0.16141938, 0.04763723],
       [0.03538336, 0.69363984, 0.85811182, 0.66621285, 0.46833453,
        0.36808472, 0.66800755, 0.08235566, 0.23996106, 0.64701117],
       [0.34107469, 0.52647235, 0.14883806, 0.38644094, 0.89674487,
        0.66957825, 0.87466694, 0.11422755, 0.78654809, 0.6199475 ],
       [0.74107565, 0.1520118 , 0.7221614

In [18]:
np.random.rand(3,3,3) #Tensor de 3x3x3

array([[[0.04752185, 0.16880554, 0.6856794 ],
        [0.75755731, 0.36495186, 0.75121741],
        [0.45340626, 0.67607854, 0.50063427]],

       [[0.66509064, 0.55095098, 0.55679665],
        [0.31526918, 0.57001083, 0.1979552 ],
        [0.53323543, 0.55037589, 0.42271254]],

       [[0.86297422, 0.06757275, 0.45691571],
        [0.13054077, 0.76635667, 0.44231728],
        [0.83116002, 0.94434333, 0.63500023]]])

In [27]:
# tmb puedo obtener enteros aleatorios entre un rango dado mediante np.random.randint
np.random.randint(23,27) #Arroja un entero entre 1 y 15

24

In [31]:
# tmb puedo completar una estructura algebraica de enteros con np.random.randint
np.random.randint(1,100,(10,10)) #Devuelve una matriz de 10x10 con numeros entreros entre el 1 y 100 de forma aleatoria

array([[63, 61, 97, 11, 52, 57, 11, 70, 98, 97],
       [54, 47, 43,  2, 33, 52, 72, 54, 42, 38],
       [20, 93, 85, 66, 50, 38, 18, 16, 40, 15],
       [76, 51, 23, 13, 29, 32, 49, 65,  9, 11],
       [22, 10, 23, 83, 65, 60, 10, 36, 68, 18],
       [38, 47, 71, 81, 69, 97, 91, 11, 53, 99],
       [58, 81, 54,  1, 94, 80,  9,  9, 41, 15],
       [78, 72, 47, 34, 84, 97, 75, 24, 49, 65],
       [62, 26, 67, 49, 28, 47, 19, 78, 20, 29],
       [51, 67, 23, 81, 87, 63, 46, 17, 25, 68]])