<a href="https://colab.research.google.com/github/Mgobeaalcoba/Pandas-y-Numpy/blob/main/dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
scalar = np.array(42)
scalar

array(42)

In [ ]:
scalar.ndim # Vemos la cantidad de dimensiones

0

In [ ]:
vector = np.array([1,2,3])
vector

array([1, 2, 3])

In [ ]:
vector.ndim # Tiene 1 dimension

1

In [ ]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
matriz.ndim #La matriz tiene 2 dimensiones

2

In [ ]:
matriz = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])
matriz


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [2, 3, 4]])

In [ ]:
matriz.ndim

2

In [ ]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9],[2,3,4]],[[1,2,3],[4,5,6],[7,8,9],[2,3,4]]])
tensor # Tensor es una matriz sobre otra matriz

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [2, 3, 4]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor4 = np.array([[[[1,2,3],[4,5,6],[7,8,9],[2,3,4]],[[1,2,3],[4,5,6],[7,8,9],[2,3,4]]],[[[1,2,3],[4,5,6],[7,8,9],[2,3,4]],[[1,2,3],[4,5,6],[7,8,9],[2,3,4]]]])
tensor4

array([[[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [2, 3, 4]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [2, 3, 4]]],


       [[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [2, 3, 4]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9],
         [2, 3, 4]]]])

In [ ]:
tensor4.ndim

4

In [ ]:
# Como agrego o elimino dimensiones
vector = np.array([1,2,3], ndmin=10)
vector

array([[[[[[[[[[1, 2, 3]]]]]]]]]])

In [ ]:
vector.ndim

10

In [ ]:
# Tmb puedo expandir la cantidad de dimensiones de mi objeto con el metodo np.expand_dims
expand = np.expand_dims(np.array([1,2,3]), axis=0) # Expando 1 dimensión como fila. 0 es fila para numpy. 1 es columna
print(expand)
expand.ndim

[[1 2 3]]


2

In [ ]:
# Y si quiero eliminar las dimensiones que no estoy usando?
print(vector, vector.ndim)
vector_2 = np.squeeze(vector) #Reduce un objeto ndimensional a un objeto de solamente las dimensiones que están en uso efectivo. 
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
