<a href="https://colab.research.google.com/github/Mgobeaalcoba/Pandas-y-Numpy/blob/main/funciones_principales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,20,10) #Vector de 10 scalares con numeros aleatorios del 1 al 20
arr

array([16,  6,  6, 13, 19,  4, 12, 14, 18, 13])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[16,  6,  6, 13, 19],
       [ 4, 12, 14, 18, 13]])

In [ ]:
#Busqueda del maximo
arr.max() 

19

In [ ]:
matriz.max(0) #Si pongo el cero me devuelve los maximos por columnas

array([16, 12, 14, 18, 19])

In [ ]:
matriz.max(1) #Si pongo el uno me devuelve los maximos por filas

array([19, 18])

In [ ]:
arr.argmax() #Indice donde se encuentra el maximo

4

In [ ]:
matriz.argmax()

4

In [ ]:
matriz.argmax(0)

array([0, 1, 1, 1, 0])

In [ ]:
matriz.argmax(1)

array([4, 3])

In [ ]:
# Si está max, está min
arr.min() 

4

In [ ]:
matriz.argmin() 

5

In [ ]:
arr.ptp() # Distancia entre pico maximo y pico minimo de mi vector o matriz

15

In [ ]:
matriz.ptp()

15

In [ ]:
matriz.ptp(0)

array([12,  6,  8,  5,  6])

In [ ]:
matriz.ptp(1)

array([13, 14])

In [ ]:
np.percentile(arr,50) #Le pido del objeto algebraico en cuestion que me devuelva el percentil que deseo. En este caso el 50 o la mediana 

13.0

In [ ]:
np.percentile(arr,0)

4.0

In [ ]:
np.percentile(arr,100)

19.0

In [ ]:
np.percentile(arr,75)

15.5

In [ ]:
np.percentile(arr,25)

7.5

In [ ]:
# Para hacer mas clara la operación con percentiles, donde deben estar ordenados, puedo ordenarlos con el codigo sort
arr.sort() #Ordena de menor a mayor
arr

array([ 4,  6,  6, 12, 13, 13, 14, 16, 18, 19])

In [ ]:
np.median(arr) # Mediana o percentil 50

13.0

In [ ]:
# Mediana de cada componente del eje 0 o columna
np.median(matriz,0)

array([ 8.5, 10. , 11. , 15. , 16. ])

In [ ]:
# Mediana de cada componente del eje 1 o fila
np.median(matriz,1)

array([ 6., 16.])

In [ ]:
np.mean(arr) # Media

12.1

In [ ]:
np.std(arr) # Desviación Std

4.928488612140643

In [ ]:
np.std(arr) ** 2

24.29

In [ ]:
np.var(arr) # Varianza o desvíación std elevada al cuadrado

24.29

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([5,6])

In [ ]:
np.concatenate((a,b),axis=0)

ValueError: ignored

In [ ]:
b = np.expand_dims(b,axis=0)

In [ ]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
np.concatenate((a,b),axis=1)

ValueError: ignored

In [ ]:
# Debo transponer para poder concatenarlas
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])