<a href="https://colab.research.google.com/github/Mgobeaalcoba/Pandas-y-Numpy/blob/main/operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
lista = [1,2]
lista

[1, 2]

In [3]:
lista * 2 # Al trabajar con listas la multiplicación las repite

[1, 2, 1, 2]

In [4]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
arr2 = arr.copy()
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2 * 2 # Al trabajar con arreglos de numpy la multiplicación se lleva adelante por cada uno de sus componentes

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr2 + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [12]:
1 / arr # me muestra el error al dividir por cero pero realiza las restantes operaciones. 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [13]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [14]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [15]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [16]:
matriz2 = matriz.copy()
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [18]:
matriz - matriz2

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [20]:
# Operación algrebaica muy muy importante que es el producto punto
# Para hacer el producto punto de 2 matrices tengo que tener dos matrices contrarias en su forma o transpuestas
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [21]:
matriz.dot(matriz2.T) #Otra forma de hacer el producto punto

array([[ 30,  80],
       [ 80, 255]])

In [22]:
matriz @ matriz2.T # Tercera forma de hacer el producto punto

array([[ 30,  80],
       [ 80, 255]])

In [23]:
np.dot(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])