<a href="https://colab.research.google.com/github/Mgobeaalcoba/Pandas-y-Numpy/blob/main/shape_y_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.random.randint(1,10,(3,2)) # El primer valor al pasar solo 2 en la estructura es la fila y el segundo las columnas. Si paso tres el primero es la profundidad
arr

array([[7, 3],
       [7, 4],
       [3, 5]])

In [ ]:
arr.shape # Me arroja las dimensiones de mi objeto algebraico en filas primero y columnas dsp

(3, 2)

In [ ]:
arr

array([[7, 3],
       [7, 4],
       [3, 5]])

In [ ]:
arr = arr.reshape(1,6) # Cambio la forma de mi array. Siempre tiene que tener la misma cantidad de datos
arr

array([[7, 3, 7, 4, 3, 5]])

In [ ]:
arr = arr.reshape(3,2)
arr

array([[7, 3],
       [7, 4],
       [3, 5]])

In [ ]:
#tmb se puede usar como metodo de np
np.reshape(arr,(1,6))

array([[7, 3, 7, 4, 3, 5]])

In [ ]:
# Hay distintas formas de re ordenar: por filas, por columnas y de forma optimizada y aleatoria entre C y F
np.reshape(arr,(2,3),'C') # Re ordena por fila

array([[7, 3, 7],
       [4, 3, 5]])

In [ ]:
np.reshape(arr,(2,3),'F') # Re ordena por columna

array([[7, 3, 4],
       [7, 3, 5]])

In [ ]:
np.reshape(arr,(2,3),'A') # Ordena de la forma mas optima para mi PC

array([[7, 3, 7],
       [4, 3, 5]])